---
- name: Install tools that don't require Ansible configuration (all)
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - rsync
    - tmux
    - git
    - openssh
    - htop
    - mupdf
    - btrfs-progs
    - wmname
    - netbrake

# See https://github.com/ansible/ansible/pull/34322 for my plan for a better
# solution
- name: Install atop using --assume-installed magic
  command: pacman --noconfirm -S atop --assume-installed cron
  when: "'atop' not in installed_packages.stdout_lines"

- name: Install tools that don't require Ansible configuration (Chris specific)
  pacman: name={{ item }} state=present
  when: not minimal
  with_items:
    - macchanger
    - python-virtualenvwrapper
    - bind-tools
    - lsof
    - whois
    - zenity  # used for trello-popup
    - dhclient  # wtf? without this ipv6 wired profiles seem to bomb
    - reflector
    - p7zip
    - maim
    - slop  # optdepends for `screenshot --select`
    - zstd
    - mercurial  # needed for some pyenv installed stuff
    - flashplugin
    - openconnect
    - mupdf-tools  # `mutool clean` to fix pdfs
    - msmtp
    - xclip
    - pass
    - sxiv
    - irssi
    # For duply
    - python2-boto
    - parallel
    - pdfpc
    - enca
    - android-tools
    - android-udev
    - hugin
    - gimp
    - gimp-plugin-gmic
    - gmic
    - rustup
    - dmidecode  # certsign
    - imagemagick
    - ghostscript # for imagemagick
    - mpv
    - ncdu
    - powertop
    - openbox  # presentations
    - libreoffice-still
    - mktorrent
    - mpd
    - mpc
    - id3v2
    - kid3
    - easytag
    - udftools
    - clang
    - shellcheck
    - docx2txt
    - antiword

- name: Install basic tools requiring aur (Chris specific)
  aur: name={{ item }}
  when: not minimal
  with_items:
    - cconv
    - duply
    - drive
    - pngquant
    - sshrc
    - spotify
    - xinput-toggle
    - nota
    - pandoc-bin
    - mpdscribble
    - mpdmenu
    - spek
    - geteltorito
    - pkgbuild-introspection
    - pdftk-bin
    - clipmenu
    - google-chrome
  become: yes
  become_user: makepkg

- name: Install bluejeans on 64-bit only
  aur: name=bluejeans
  become: yes
  become_user: makepkg
  when: long_bit.stdout == "64" and not minimal

- name: Install laptop tools
  aur: name={{ item }}
  with_items:
    - bats
  when: laptop
  become: yes
  become_user: makepkg

- name: Unmask rtkit
  systemd: name={{ item }} state=started enabled=yes masked=no
  with_items:
    - rtkit-daemon
    - polkit
