---
- name: Install debugging tools
  pacman: name={{ item }} state=present
  with_items:
    - bind-tools
    - htop
    - iftop
    - mtr
    - strace
    - time
    - ngrep
    - perf

- name: Install debugging tools (AUR)
  aur: name={{ item }}
  with_items:
    - bcc-tools
    - python2-bcc
  become: yes
  become_user: makepkg

- name: Copy atop config
  copy: src=files/atop.daily dest=/usr/share/atop/atop.daily mode=700

- name: Mask atop
  systemd: name=atop state=stopped enabled=no masked=yes
