---
- name: Install PGP keys for kernel build
  command: gpg --recv-keys {{ item }}
  with_items: "{{ extra_kernel_pgp_keys }}"
  become: yes
  become_user: makepkg

- name: Install kernel
  aur: name={{ item }} state=present
  become: yes
  become_user: makepkg
  with_items:
    - "{{ kernel }}"
    - "{{ kernel }}-headers"

- name: For whatever kernel we installed, add standard + LTS ones as a backup
  pacman: name={{ item }} state=present
  with_items:
    - linux
    - linux-headers
    - linux-lts
    - linux-lts-headers
  when: not minimal

- name: Install mkinitcpio config
  copy: src=files/mkinitcpio.conf dest=/etc/mkinitcpio.conf
  register: cpio

- name: Regenerate initcpios
  command: mkinitcpio -P
  when: cpio.changed
